### PR TITLE
[#9] Implement TOML codec using Generics

### LINKED ISSUE #3: Decide on the config format
Most likely we will use `tomland` and TOML.
The structure tbd

### LINKED ISSUE #9: Create TOML Codec

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #3 
Resolves #9

I'm using generic codec from `tomland`. It works! Maybe currently usage is not that convenient because there are limits in GHC. But this is the best I can do now...

```haskell
λ: TIO.putStrLn $ Toml.encode stripTypeNameCodec (Work "developer" (Company "foo" "bar") (fromGregorian 2019 1 1) Nothing (Just (Location "x" "y")) "quux")
description = "quux"
position = "developer"
start = 2019-01-01

[company]
  link = "bar"
  name = "foo"

[location]
  city = "y"
  country = "x"
```

Currently it uses specific `tomland` commit. Once a new version of `tomland` is released, I can remove `cabal.project`

### CODE REVIEW

**Comment by vrom911** [comment]
@chshersh apologies for the delayed review :slightly_frowning_face:  I really appreciate your work here! 

As we released a new version, could you please update on that here?

**Comment by chshersh** [comment]
@vrom911 Sure! I will update the PR to use `tomland` version from Hackage 👍

**Comment by chshersh** [comment]
@vrom911 Done :+1: I've also updated `.travis.yml` and `.cabal` files

**Review by vrom911 — APPROVED** [review]
Amazing!

**Pull request merged**
